//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsFormPublica.wsPublicacao {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPublicacao.WebServiceFrameworkSoap")]
    public interface WebServiceFrameworkSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Consultar(out string mensagem, string usuario, string consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncluirPublicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IncluirPublicacao(out string mensagem, wsFormPublica.wsPublicacao.DadosPublicacao dados, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Autenticar(string usuario);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosPublicacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tituloField;
        
        private string autoresField;
        
        private string palavrasChaveField;
        
        private System.DateTime dataField;
        
        private string publicacaoField;
        
        private string editorField;
        
        private string enderecoEletronicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Autores {
            get {
                return this.autoresField;
            }
            set {
                this.autoresField = value;
                this.RaisePropertyChanged("Autores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PalavrasChave {
            get {
                return this.palavrasChaveField;
            }
            set {
                this.palavrasChaveField = value;
                this.RaisePropertyChanged("PalavrasChave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Publicacao {
            get {
                return this.publicacaoField;
            }
            set {
                this.publicacaoField = value;
                this.RaisePropertyChanged("Publicacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
                this.RaisePropertyChanged("Editor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EnderecoEletronico {
            get {
                return this.enderecoEletronicoField;
            }
            set {
                this.enderecoEletronicoField = value;
                this.RaisePropertyChanged("EnderecoEletronico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFrameworkSoapChannel : wsFormPublica.wsPublicacao.WebServiceFrameworkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFrameworkSoapClient : System.ServiceModel.ClientBase<wsFormPublica.wsPublicacao.WebServiceFrameworkSoap>, wsFormPublica.wsPublicacao.WebServiceFrameworkSoap {
        
        public WebServiceFrameworkSoapClient() {
        }
        
        public WebServiceFrameworkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFrameworkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFrameworkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFrameworkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable Consultar(out string mensagem, string usuario, string consulta) {
            return base.Channel.Consultar(out mensagem, usuario, consulta);
        }
        
        public bool IncluirPublicacao(out string mensagem, wsFormPublica.wsPublicacao.DadosPublicacao dados, string usuario) {
            return base.Channel.IncluirPublicacao(out mensagem, dados, usuario);
        }
        
        public bool Autenticar(string usuario) {
            return base.Channel.Autenticar(usuario);
        }
    }
}
